<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSWHUxse\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSWHUxse/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerSWHUxse.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerSWHUxse\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerSWHUxse\App_KernelProdContainer([
    'container.build_hash' => 'SWHUxse',
    'container.build_id' => '1f026d9a',
    'container.build_time' => 1644575623,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSWHUxse');
