<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXjnkggZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXjnkggZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXjnkggZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXjnkggZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXjnkggZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'XjnkggZ',
    'container.build_id' => 'fe2d61d2',
    'container.build_time' => 1645179360,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXjnkggZ');
